import { ThemeProvider } from 'next-themes';
import Header from '@/components/header/Header';
import "./globals.css";
import AuthContextProvider from '@/lib/contexts/AuthContext';
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class">
        <AuthContextProvider>
          {/* <Header/> */}
          {children}
          </AuthContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}