import { ThemeProvider } from 'next-themes';
import Header from '@/components/header/Header';
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class">
          <Header/>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}